Repository voxpupuli/pypuppetdb, pull requests merged in 2020-03, with the labels that each got.

#173 Switch to Metrics API v2
  pypuppetdb/api.py
  tests/test_baseapi.py
Labels: bug

#175 Metrics v2 fixes
  CHANGELOG.rst
  pypuppetdb/api.py
  tests/test_baseapi.py
Labels: bug, enhancement

#176 Release 2.1.0 version bump
  CHANGELOG.rst
  python-pypuppetdb.spec
  version
Labels: skip-changelog
